version: "3"

tasks:
  sync:
    desc: Sync project dependencies with uv
    cmds:
      - uv sync --extra dev
  style:
    desc: Run Ruff autofix, format, then MyPy
    deps: [sync]
    cmds:
      - uv run ruff check . --fix
      - uv run ruff format .
  track:
    desc: Train and log experiment via MLFlow
    deps: [sync]
    cmds:
      - |
        uv run python main.py track \
          --experiment ${EXPERIMENT:-housing-prices} \
          ${RUN_NAME:+--run-name "$RUN_NAME"}
  mlflow-ui:
    desc: Launch the MLFlow local UI
    deps: [sync]
    cmds:
      - uv run mlflow ui --backend-store-uri ./mlruns
