version: "3"
dotenv: [".env"]

tasks:
  sync:
    desc: Sync project dependencies with uv
    cmds:
      - uv sync --extra dev
  style:
    desc: Run Ruff autofix, format, then MyPy
    deps: [sync]
    cmds:
      - uv run ruff check . --fix
      - uv run ruff format .
  ingest:
    desc: Ingest Bitcoin candles via Binance and store them in DuckDB
    deps: [sync]
    cmds:
      - |
        uv run python main.py ingest
  track:
    desc: Train and log experiment via MLFlow
    deps: [sync]
    cmds:
      - |
        uv run python main.py track \
          --experiment ${EXPERIMENT:-bitcoin_preds} \
          ${RUN_NAME:+--run-name "$RUN_NAME"}
  register:
    desc: Register a tracked run's model in the MLFlow registry
    deps: [sync]
    cmds:
      - |
        uv run python main.py register \
          --run-id ${RUN_ID:?RUN_ID required} \
          --model-name ${MODEL_NAME:-housing-prices-model} \
          ${MODEL_ALIAS:+--alias "$MODEL_ALIAS"}
  api:
    desc: Launch the FastAPI inference service
    deps: [sync]
    cmds:
      - |
        export MODEL_URI=${MODEL_URI:-models:/bitcoin-model@production}
        export API_HOST=${API_HOST:-0.0.0.0}
        export API_PORT=${API_PORT:-8000}
        uv run uvicorn api.app:app --host "$API_HOST" --port "$API_PORT"
  mlflow-ui:
    desc: Launch the MLFlow local UI
    deps: [sync]
    cmds:
      - uv run mlflow ui --backend-store-uri ./mlruns
