version: "3"

tasks:
  sync:
    desc: Sync project dependencies with uv
    cmds:
      - uv sync --extra dev
  run:
    desc: Execute the app via uv
    cmds:
      - uv run main.py
  style:
    desc: Run Ruff autofix, format, then MyPy
    deps: [sync]
    cmds:
      - uv run ruff check . --fix
      - uv run ruff format .
