version: "3"

tasks:
  sync:
    desc: Sync project dependencies with uv
    cmds:
      - uv sync
  run:
    desc: Execute the app via uv
    cmds:
      - uv run main.py
  style:
    desc: Run Ruff, MyPy, and Black in a single pass
    deps: [sync]
    cmds:
      - "uv run --group dev bash -lc 'ruff check . && mypy . && black .'"
